server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/ai/**

        - id: interview-service
          uri: lb://interview-service
          predicates:
            - Path=/interview/**

        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/analytics/**